spring.application.name=api
server.port=8093
spring.datasource.url=jdbc:postgresql://localhost:5432/figure_store_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
app.admin.username=${ADMIN_USERNAME:admin}
app.admin.password=${ADMIN_PASSWORD:change-me}
app.payment-expiry.interval-ms=60000
midtrans.server-key=${MIDTRANS_SERVER_KEY:SB-Mid-server-xxxx}
midtrans.client-key=${MIDTRANS_CLIENT_KEY:SB-Mid-client-xxxx}
midtrans.is-production=false
